### ISSUE TITLE
No Menu items in top bar

### ISSUE THREAD

**Issue by bmentink** [kvormweg/wallpaper#3]
I cannot get any menu items to show, either using auto generated or using a "menu" page at the top level namespace.

**Comment by bmentink** [comment]
Ah!! I see you have to enable "create a submenu for pages in the root namespace" for anything to show at all .. when that is turned on, I get a menu that reflects my menu.txt page ... 

I am not sure if that is a bug or not ..

**Comment by kvormweg** [comment]
No, it's a bug. The menu should work whether the flag "create a submenu for pages in the root namespace" is set or not. A bug fix is in progress.

**Comment by kvormweg** [comment]
This issue should be resolved with release 0.10.4
